brew "aria2"
brew "cmake"
brew "coreutils"
brew "docker"
brew "git"
brew "git-flow"
brew "git-lfs"
brew "gnupg"
brew "htop"
brew "jq"
brew "make"
brew "mas"
brew "rbenv"
brew "rust"
brew "sdl2"
brew "sdl2_image"
brew "sdl2_ttf"
brew "trash"
brew "vsce"
brew "watch"
brew "xcodes"
brew "zsh-completions"

cask "audacity"
cask "balenaetcher"
cask "discord"
cask "gimp"
cask "git-credential-manager"
cask "google-drive"
cask "keepassxc"
cask "porting-kit"
cask "reaper"
cask "tiles"
cask "virtualbox@beta"
cask "visual-studio-code"
cask "whisky"

mas "AdGuard for Safari", id: 1440147259
mas "Cleaner for Xcode", id: 1296084683

vscode "eamodio.gitlens"
vscode "mads-hartmann.bash-ide-vscode"
vscode "mattmaniak.inkpot-gc-vsc"
vscode "ms-python.python"
vscode "ms-vscode.cpptools"
vscode "ms-vscode.makefile-tools"
